apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test
    image: vault:mine3
    command: ["sleep", "3600"]
    volumeMounts:
    - name: scripts
      mountPath: /scripts
  volumes:
  - name: scripts
    persistentVolumeClaim:
      claimName: data-fk-vault-0
