
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radar
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radar
  template:
    metadata:
      labels:
        app: radar
    spec:
      serviceAccountName: radar
      containers:
      - name: radar
        image: ghcr.io/skyhook-io/radar:latest
        ports:
        - containerPort: 9281
---

apiVersion: v1
kind: Service
metadata:
  name: radar
spec:
  selector:
    app: radar
  ports:
  - port: 80
    targetPort: 9280

