{{- template "vault.webhook2_cleanerEnabled" . -}}
{{- if .webhook2_cleanerEnabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault.fullname" . }}-webhook2-cleaner
  namespace: {{ include "vault.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-webhook2-cleaner
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{ template "injector.serviceAccount.annotations" . }}
{{ end }}