{{- template "vault.webhook2_cleanerEnabled" . -}}
{{- if .webhook2_cleanerEnabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "vault.fullname" . }}-webhook2-cleaner-binding
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-webhook2-cleaner
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "vault.fullname" . }}-webhook2-cleaner-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ template "vault.fullname" . }}-webhook2-cleaner
  namespace: {{ include "vault.namespace" . }}
{{ end }}